### PR TITLE
[WIP] Fix username link

### LINKED ISSUE #112: Fix link when clicking on username
The usernames link to `/team/<user-id>`, which 404s. I think those links used to go to `https://clojurians.slack.com/team/<user-id>`, but that we broke that at some point.

However instead of linking back to slack I think it would be better to just display user/profile information on our end. Slack uses an overlay panel for this. Having a standalone route would be fine though, we can maybe sprinkle in some javascript later to make it into an overlay.

### PR DESCRIPTION
**Pull request by oxalorg**
Implement a separate "user-profile" route

Fixes #112

### CODE REVIEW

**Comment by oxalorg** [comment]
We've completed Phase 1 as described here:

> 
> 
> As per our call's discussion, @ArielA147 we've divided this task into two phases.
> 
>     1. Create a route and return a simple "Hello {username}" html
> 
>     2. Figure out the db/queries to make the final page
> 
> 
> For the first phase we need to do the following steps:
> 
> Steps we need to take to get :
> 
>     1. Create a new route mapping in `routes/routes` -> Something like `/users/x/x/{user-id}`
> 
>     2. Create a new route function which takes a request (you can probably name it something like `user-profile-route`
> 
>     3. Create a context in that function
> 
>     4. Add a `:data/username` attribute to the context and fill it with the `user-id` url parameter (from `:request` map which we explored)
> 
>     5. Pass this context to a view and add a `:response/html` attribute with a hiccup data structure
> 
>     6. Finally render the response

**Comment by plexus** [comment]
Good start! make sure to take out the `(def request request)` when you're done ;)

**Comment by plexus** [comment]
Hey, I was just having a quick look how this is going. It seems `src/clojurians_log/repl.clj` was deleted? And the executable flag removed from `bin/*`?

**Comment by ArielA147** [comment]
> Hey, I was just having a quick look how this is going. It seems `src/clojurians_log/repl.clj` was deleted? And the executable flag removed from `bin/*`?

I uploaded by mistake my local files instead of using the project files, this is way I delete the files I uploaded.

File: src/clojurians_log/views.clj [hunk 1]
```diff
@@ -178,16 +178,17 @@
...
         slack-instance (:clojurians-log.application/slack-instance request)]
 
     ;; things in the profile
     ;; :image_512 :email :real_name_normalized :image_48 :image_192 :real_name :image_72 :image_24
     ;; :avatar_hash :title :team :image_32 :display_name :display_name_normalized
     (list [:div.message
            {:id (cl.tu/format-inst-id inst) :class (when (thread-child? message) "thread-msg")}
-           [:a.message_profile-pic {:href (str slack-instance "/team/" slack-id) :style (str "background-image: url(" image-48 ");")}]
-           [:a.message_username {:href (str slack-instance "/team/" slack-id)}
+          [:a.message_profile-pic {:href (str slack-instance "/users/x/x/" slack-id) :style (str "background-image: url(" image-192 ");")}]
```
Comment (oxalorg) [inline src/clojurians_log/views.clj:189]: Does this need to be image-192? It can be image-48?

File: src/clojurians_log/db/queries.clj [hunk 2]
```diff
@@ -109,6 +109,18 @@
        db
        ids))
 
+(defn user-profile
+    "returing all the data about the user acording to the user id slack number"
+    [db id]
+  (first
+ (d/q '[:find
```
Comment (plexus) [inline src/clojurians_log/db/queries.clj:116]: something went wrong with the indentation here :)

File: src/clojurians_log/views.clj [hunk 3]
```diff
@@ -280,6 +281,28 @@
...
+                              [:user-profile/display-name :user-profile/real-name :user-profile/image-192 :user/slack-id])
+           :when (-> k)]
+       (case k
+         :user-profile/image-192 [:img {:src [v], :alt "John", :style "width:95%; border-radius:80%; padding: 8px 0px;"}]
+         :user-profile/display-name [:h1 [k v]]
+         :user-profile/real-name [:p {:style "color: grey; font-size: 18px;"} [k v]]
+         :user/slack-id [:a {:style "border: none; outline: 0; display: inline-block; padding: 8px 0px; 
+                                    color: white; background-color: #000; text-align: center; cursor: pointer; 
+                                    width: 100%; font-size: 18px;"
+                             :href (str "https://clojurians.slack.com//team/" v )} "let's talk on Slack"]
```
Comment (plexus) [inline src/clojurians_log/views.clj:301]: Use `slack-instance` here instead of hardcoding `clojurians.slack.com`, we also use this app for slack instances that are not clojurians. See `single-message` (line 182) for how to get the `slack-instance`.

File: src/clojurians_log/views.clj [hunk 4]
```diff
@@ -280,6 +281,28 @@
...
+         )
+       )   
+     ]]])
```
Comment (plexus) [inline src/clojurians_log/views.clj:304]: Try not to have too many of these lonely parens, they belong with their friends at the end of line 301.

**Comment by plexus** [comment]
I left a few comments, the only real blocker for me is the hard-coded `clojurians.slack.com`, apart from that this is good to go.

**Comment by ArielA147** [comment]
@plexus @oxalorg - from my side this is good to go

File: src/clojurians_log/views.clj [hunk 5]
```diff
@@ -178,16 +178,17 @@
    {:message/keys [user inst user text thread-ts ts] :as message}]
 
   (let [{:user/keys         [name slack-id]
-         :user-profile/keys [display-name real-name image-48]} user
-        slack-instance (:clojurians-log.application/slack-instance request)]
+         :user-profile/keys [display-name real-name image-48]} user]    
+    (def slack-instance (:clojurians-log.application/slack-instance request))
```
Comment (plexus) [inline src/clojurians_log/views.clj:182]: I'm guessing this was for debugging? let's move that back into the let.

File: src/clojurians_log/views.clj [hunk 6]
```diff
@@ -280,6 +281,25 @@
...
+                              [:user-profile/display-name :user-profile/real-name :user-profile/image-192 :user/slack-id])
+           :when (-> k)]
+       (case k
+         :user-profile/image-192 [:img {:src [v], :alt "John", :style "width:95%; border-radius:80%; padding: 8px 0px;"}]
+         :user-profile/display-name [:h1 [k v]]
+         :user-profile/real-name [:p {:style "color: grey; font-size: 18px;"} [k v]]
+         :user/slack-id [:a {:style "border: none; outline: 0; display: inline-block; padding: 8px 0px; 
+                                    color: white; background-color: #000; text-align: center; cursor: pointer; 
+                                    width: 100%; font-size: 18px;"
+                             :href (str slack-instance "/team/" v )} "let's talk on Slack"]))]]])
```
Comment (plexus) [inline src/clojurians_log/views.clj:301]: Quite an original solution! I guess the `select-keys` also ensures the ordering? I would do this a lot less clever.

```
(let [{:user-profile/keys [display-name real-name image-192] :user/keys [slack-id]} (get-in context [:data/username 0])]
  (list
    (when image-192
      [:img {:src image-192} ...])
    (when display-name
      [:h1 display-name])
    ...
```

Some other notes here
- `:alt "John"` I guess not everyone is called John :)
- `:src [v]` what's that vector doing? Just `:src v` should be fine
- `[:h1 [k v]]` that inner vector is definitely not right, this will end up in html as `<h1><user-profile/display-name>...</user-profile/display-name></h1>`
- inline styling -> styles.clj :see_no_evil: 
- Why is it `:data/username` when what's in there is a whole bunch of user profile information? shouldn't it then be `:data/user-profile`? Why the `0` in the `get-in`?

File: src/clojurians_log/routes.clj [hunk 7]
```diff
@@ -132,6 +132,15 @@
       views/about
       response/render))
 
+(defn user-profile-route  [{:keys [endpoint] :as request}]
+    (let [db (db-from-endpoint endpoint)]
+      (-> request
+          make-context
+          (assoc :data/username
```
Comment (plexus) [inline src/clojurians_log/routes.clj:139]: I would expect to find a `username` under `:data/username`, can we call this `:data/user-profile`?

File: src/clojurians_log/db/queries.clj [hunk 8]
```diff
@@ -109,6 +109,15 @@
...
        ids))
 
+(defn user-profile
+  "returing all the data about the user acording to the user id slack number"
+  [db id]
+  (first (d/q '[:find (pull ?user [*])
+                :in $ ?id
+                :where [?user :user/slack-id ?id]]
+              db
+              id)))
```
Comment (plexus) [inline src/clojurians_log/db/queries.clj:119]: Is this returning a single map or a sequence of maps? If it's a sequence can we change it to just return a single map? that will make lookup later more straightforward. I think adding a `.` at the end of line 115 might be enough.

File: src/clojurians_log/routes.clj [hunk 9]
```diff
@@ -156,16 +165,22 @@
...
+   ["/{channel}/{date}" {:name :clojurians-log.routes/channel-date
                          :get log-route}]
-   ["/{channel}/{date}/{ts}" {:name :clojurians-log.routes/message,
-                              :get log-route}]
-   ["/_/stats/{from-date}/{to-date}" {:name :clojurians-log.routes/message-stats :get message-stats-route}]])
+   ["/{channel}/{date}/{ts}" {:name :clojurians-log.routes/message :get log-route}]
+   ["/_/stats/{from-date}/{to-date}" {:name :clojurians-log.routes/message-stats 
+                                      :get message-stats-route}]
+
+   {:conflicts nil}
```
Comment (plexus) [inline src/clojurians_log/routes.clj:184]: Is this still needed?

**Review by plexus — CHANGES_REQUESTED** [review]
Good effort Ariel! Thanks! I left some feedback on things I noticed, let's try to improve this a little still.

File: src/clojurians_log/routes.clj (hunk 9 above)
Comment (ArielA147) [reply src/clojurians_log/routes.clj:184]: No, changing the route for the user profile page to "/_/_/users/{user-id}" fixed this.

File: src/clojurians_log/routes.clj (hunk 7 above)
Comment (ArielA147) [reply src/clojurians_log/routes.clj:139]: yes, you are right.
I will change this.
